a1/laravelEcom/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::post('transactions/paypal/create', 'TransactionsController@paypal_store')->name('paypal.store');

Route::delete('/carts/clear', 'CartController@removeCart')->name('carts.clear');
Route::get('/', 'ProductsController@index')->name('home');

Route::resource('products', 'ProductsController');
Route::resource('categories', 'CategoriesController');
Route::resource('transactions', 'TransactionsController');
Route::resource('carts', 'CartController');

a1/laravelEcom/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\SoftDeletes;
class Product extends Model
{
	use SoftDeletes;

	public function category(){
		return $this->belongsTo('App\Category');
	}
}

a1/laravelEcom/app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Category;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Product $product)
    {
        $products = $product->all();
        return view('products.index')->with('products', $products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category)
    {
        $this->authorize('create', Product::class);

        $category = $category->all();
        // $category = Category::all();
        return view('products.create')->with('categories', $category);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|min:4',
            'price' => 'required|numeric|digits_between:1,8',
            'category' => 'required',
            'image' => 'required|image|max:4000|mimes:jpeg,jpg,png,gif',
            'description' => 'required|string',
        ]);

        $file = $request->file('image');
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
        $file_extension = $file->extension();
        
        $random_name = Str::random(10);

        $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_name . "_" . $file_name . "." . $file_extension;

        $filepath = $file->storeAs('images', $new_file_name, 'public');
        
        // dd($new_file_name);

        $name = $request->input('name');
        $price = $request->input('price');
        $category_id = $request->input('category');
        $description = $request->input('description');
        $image = $filepath;

        $product = new Product;

        $product->name = $name;
        $product->price = $price;
        $product->category_id = $category_id;
        $product->description = $description;
        $product->image = $image;

        $product->save();

        return redirect( route('products.show', ['product' => $product->id] ) );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show')->with('product', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $this->authorize('update', $product);
        
        $category = Category::all();
        return view('products.edit')
            ->with('product', $product)
            ->with('categories', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $this->authorize('update', $product);
         $request->validate([
            'name' => 'required|string|min:4',
            'price' => 'required|numeric|digits_between:1,8',
            'category' => 'required',
            // 'image' => 'required|image|max:4000|mimes:jpeg,jpg,png,gif',
            'description' => 'required|string',
        ]);

        if(
            !$request->hasFile('image') &&
            $product->name == $request->input('name') &&
            $product->description == $request->input('description') &&
            $product->price == $request->input('price') &&
            $product->category_id == $request->input('category')
        ) {
            $request->session()->flash('update_failed', 'Wala kang binago eh???');

            // return redirect( route('products.edit', ['product' => $product->id]));
        } else {
            // echo "awit";

            if($request->hasFile('image')) {
                $request->validate([
                    'image' => 'required|image|max:4000|mimes:jpeg,jpg,png,gif',
                ]);

                $file = $request->file('image');
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $file_extension = $file->extension();
                
                $random_name = Str::random(10);

                $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_name . "_" . $file_name . "." . $file_extension;

                $filepath = $file->storeAs('images', $new_file_name, 'public');

                $product->image = $filepath;
            }

            $product->name = $request->input('name');
            $product->price = $request->input('price');
            $product->description = $request->input('description');
            $product->category_id = $request->input('category');
            
            $product->save();

            $request->session()->flash('update_success', 'Congrats, updated na ang iyong product');
        }
            return redirect( route('products.edit', ['product' => $product->id]));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->authorize('delete', $product);
        $product->delete();
        // $request->session()->flash('product_deleted', 'AWIT, na delete na nga!!');
        return redirect(route('products.index'))->with('product_deleted', 'AWIT nga, na delete na nga?!');
    }
}

a1/laravelEcom/resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
	

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<div class="jumbotron">
					<h3 class="text-center">Add New Product</h3>
					<hr>
					<form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
						@csrf
						
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="name"> Product Name</label>
									<input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
								</div>
								@if($errors->has('name'))
								<p>
									<small class="alert alert-danger">
										@foreach($errors->get('name') as $error)
											{{ $error }}
										@endforeach
									</small>
								</p>
								@endif
							</div>
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="price"> Product Price</label>
									<input type="number" name="price" id="price" class="form-control" min="1" value="{{ old('price') }}">
								</div>
								@if($errors->has('price'))
								<p>
									<small class="alert alert-danger">
										@foreach($errors->get('price') as $error)
											{{ $error }}
										@endforeach
									</small>
								</p>
								@endif
							</div>

							<div class="col-md-12">
								<div class="form-group">
									<label for="category"> Category </label>
									<select name="category" id="category" class="form-control">
										@foreach($categories as $category)
										<option value="{{ $category->id }}">{{ $category->name }}</option>
										@endforeach
									</select>
								</div>
							</div>

							<div class="col-md-12">
								<div class="form-group">
									<label for="image"> Product Image</label>
									<input type="file" name="image" id="image" class="form-control-file">
								</div>
								@if($errors->has('image'))
								<p>
									<small class="alert alert-danger">
										@foreach($errors->get('image') as $error)
											{{ $error }}
										@endforeach
									</small>
								</p>
								@endif
							</div>

							<div class="col-md-12">
								<div class="form-group">
									<label for="description"> Description</label>
									<textarea name="description" id="description" class="form-control" rows="10">{{ old('description') }}</textarea>
								</div>
								@if($errors->has('description'))
								<p>
									<small class="alert alert-danger">
										@foreach($errors->get('description') as $error)
											{{ $error }}
										@endforeach
									</small>
								</p>
								@endif
							</div>

							<div class="col-md-12">
								<button class="btn btn-outline-dark w-50 float-right">Add Item</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			
			<div class="col-12 col-md-4 mx-auto">
				<h3>Add New Category</h3>
				<hr>
				@if(Session::has('category_message'))
					<div class="alert alert-success">
						{{ Session::get('category_message') }}
					</div>
				@endif
				@if($errors->has('add-category'))
					<p>
						<small class="alert alert-danger">
							@foreach($errors->get('add-category') as $error)
								{{ old('add-category') }} {{ $error }}
							@endforeach
						</small>
					</p>
				@endif
				<form action="{{ route('categories.store') }}" method="POST">
					@csrf
					<div class="form-group">
						<label for="add-category"> Add New Category </label>
						<input type="text" name="add-category" id="add-category" class="form-control">
					</div>

					<button class="btn btn-secondary float-right">Add Category</button>
				</form>
			</div>
		</div>
	</div>


@endsection

a1/laravelEcom/resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
	

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<div class="jumbotron">
					<h3 class="text-center">Edit ka product??</h3>
					@if(Session::has('update_failed'))
						<div class="alert alert-warning">
							{{ Session::get('update_failed')}}
						</div>
					@endif
					@if(Session::has('update_success'))
						<div class="alert alert-success">
							{{ Session::get('update_success')}}
						</div>
					@endif
					<hr>
					<form action="{{ route('products.update', ['product' => $product->id]) }}" method="POST" enctype="multipart/form-data">
						@csrf
						@method("PUT")
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="name"> Product Name</label>
									<input type="text" name="name" id="name" class="form-control" value="{{ $product->name }}">
								</div>
							</div>
							
							<div class="col-md-6">
								<div class="form-group">
									<label for="price"> Product Price</label>
									<input type="number" name="price" id="price" class="form-control" min="1" value="{{ $product->price }}">
								</div>
							</div>

							<div class="col-md-12">
								<div class="form-group">
									<label for="category"> Category </label>
									<select name="category" id="category" class="form-control">
										@foreach($categories as $category)
											<option value="{{ $category->id }}"
													@if($product->category_id == $category->id)
														selected
													@endif>
													{{ $category->name }}
											</option>
										@endforeach
									</select>
								</div>
							</div>

							<div class="col-md-12">
								<div class="form-group">
									<label for="image"> Product Image</label>
									<input type="file" name="image" id="image" class="form-control-file">
									<img src="{{ url('/public/' . $product->image) }}" class="img-fluid">
								</div>
							</div>

							<div class="col-md-12">
								<div class="form-group">
									<label for="description"> Description</label>
									<textarea name="description" id="description" class="form-control" rows="10">{{ $product->description }}</textarea>
								</div>
							</div>

							<div class="col-md-12">
								<button class="btn btn-outline-dark w-50 float-right"> Edith Mo To??</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>


@endsection

a1/laravelEcom/resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="jumbotron">
			<h3 class="text-center">Products</h3>
			<hr>
			@if(Session::has('product_deleted'))
				<div class="alert alert-danger">
					{{ Session::get('product_deleted')}}
				</div>
			@endif
			<div class="row">
				@foreach($products as $product)
					<div class="col-md-6 d-flex">
						<div class="card">
							<div class="card-header">
								<img class="card-img-top img-thumbnail img-fluid" src="{{ url('/public/'.$product->image) }}">
							</div>

							<div class="card-body">
								
								<h4 class="card-title mx-auto">{{ $product->category->name }}</h4>

								<strong><p class="card-text">&#8369; {{ $product->price}}</p></strong>
								<p class="card-text">{{ $product->description}}</p>
							</div>

							<div class="card-footer">
								@can('isAdmin')
								
								@else 
									<form action="{{ route('carts.store') }}" method="POST" class="add-to-cart-field">
										@csrf
										<input type="hidden" name="id" value="{{ $product->id }}">
										<div class="form-inline">
											<label for="quantity">Quantity: </label>
											<div class="input-group mb-2">
												<div class="input-group-prepend">
													<button type="button" class="btn btn-outline-danger deduct-quantity" data-id={{ $product->id }}> - </button>
												</div>

												<input type="number" value="1" class="form-control input-quantity" name="quantity" id="quantity" placeholder="Enter quantity" data-id={{ $product->id }}>

												<div class="input-group-append">
													<button type="button" class="btn btn-outline-info add-quantity" data-id={{ $product->id }}> + </button>
												</div>
											</div>
											<button class="btn btn-success btn-block mb-2">Add to Cart</button>
										</div>
									</form>
								@endcan
								
								<a href="{{ route('products.show', ['product' => $product->id] )}}" class="btn btn-outline-info btn-block mb-2">View Details</a>

								@can('isAdmin')
									<a href="{{ route('products.edit', ['product' => $product->id] )}}" class="btn btn-primary btn-block mb-2">Edit Details</a>

									<form action="{{ route('products.destroy', ['product' => $product->id] )}}" method="POST">
										@csrf
										@method('DELETE')
										<button class="btn btn-outline-danger btn-block">Delete</button>
									</form>
								@endcan
							</div>
						</div>
					</div>
				@endforeach
			</div>
		</div>
	</div>


@endsection

a1/laravelEcom/resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="jumbotron">
			<div class="row">
				<div class="col-12 col-md-8 mx-auto">
					<h3 class="text-center">Product Details</h3>
					<hr>
				</div>

				<div class="col-md-12">
					<div class="row">
						<div class="col-md-6 col-12 mx-auto">
							<div class="card mx-auto">
						<div class="card-header">
								<img class="card-img-top img-thumbnail img-fluid" src="{{ url('/public/'.$product->image) }}">
							</div>

						<div class="card-body">
							<h4 class="card-title mx-auto">{{ $product->name }}</h4>
							<strong><p class="card-text">&#8369; {{ $product->price}}</p></strong>
							<p class="card-text">{{ $product->description}}</p>
						</div>

						<div class="card-footer">
							@can('isAdmin')
								<a href="{{ route('products.edit', ['product' => $product->id] )}}" class="btn btn-primary btn-block mb-2">Edit Details</a>

								<form action="{{ route('products.destroy', ['product' => $product->id] )}}" method="POST">
								@csrf
								@method('DELETE')
									<button class="btn btn-outline-danger btn-block">Delete</button>
								</form>
							@else
								<form action="{{ route('carts.store') }}" method="POST" class="add-to-cart-field">
									@csrf
									<input type="hidden" name="id" value="{{ $product->id }}">
									<div class="form-inline">
										<label for="quantity">Quantity: </label>
										<div class="input-group mb-2">
											<div class="input-group-prepend">
												<button type="button" class="btn btn-outline-danger deduct-quantity" data-id={{ $product->id }}> - </button>
											</div>

											<input type="number" class="form-control input-quantity" name="quantity" id="quantity" placeholder="Enter quantity" data-id={{ $product->id }}>

											<div class="input-group-append">
												<button type="button" class="btn btn-outline-info add-quantity" data-id={{ $product->id }}> + </button>
											</div>
										</div>
										<button class="btn btn-success btn-block mb-2">Add to Cart</button>
									</div>
								</form>
							@endcan
						</div>
					</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


@endsection