d1/sampleProject/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", 'PagesController@index');
Route::get("/about", 'PagesController@about')->name('about');
Route::get("/services", 'PagesController@services')->name('services');



// Route::get('/posts', 'PostsController@index')->name('posts.index');
// Route::get('/posts/create', 'PostsController@create')->name('posts.create');
// Route::post('/posts', 'PostsController@store')->name('posts.store');
// Route::get('/posts/{post}', 'PostsController@show')->name('posts.show');
// Route::put('/posts/{post}', 'PostController@update');

Route::resource('posts', 'PostsController');

d1/sampleProject/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}

d1/sampleProject/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

d1/sampleProject/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

d1/sampleProject/app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    public function index() {
        $title = 'Welcome to Larabel';
        return view('pages.index')->with('title',$title);   
    }

    public function about() {
        $title = 'About Page';
        return view('pages.about', ['title' => $title]); 
    }

    public function services() {
        $data = [
            'title' => 'Services Page',
            'services' => [
                'Web Design',
                'Development',
                'SEO'
            ]
        ];
        return view('pages.services', $data);  
    }
}

d1/sampleProject/app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|min:4',
            'body' => 'required',
        ]);

        $title = $request->input('title'); // <- $_POST['name'];
        $body = $request->input('body');

        $post = new Post;
        $post->title = $title;
        $post->body = $body;
        $post->save();

        return redirect( route('posts.show', ['post' => $post->id]) );

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($post)
    {
        $post = Post::find($post);
        return view('posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        // $post = Post::find($post);
        return view('posts.edit')->with('post', $post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'title' => 'required|string|min:4',
            'body' => 'required',
        ]);

        $post->title = $request->input('title');
        $post->body = $request->input('body');
        $post->save();

        return redirect( route('posts.show', ["post" => $post->id]) ); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect( route('posts.index') );
    }
}

d1/sampleProject/resources/views/bye.blade.php
<h1>

	BYE BYE !! :P

	{{ $front_end }}
</h1>


{{ $topics['0']}}

@foreach($topics as $topic)
	<p>{{$topic}}</p>

@endforeach


@if(count($topics) > 0 )
	
	<p> {{ dd($topics)}} </p>

@else
	<p> uwu </p>
@endif

d1/sampleProject/resources/views/hello.blade.php
<h1>
	TEMPLATE FROM PAGESCONTROLLER
</h1>

d1/sampleProject/resources/views/inc/navbar.blade.php
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <a class="navbar-brand" href="/">LARABEL</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#burgerMoto" aria-controls="burgerMoto">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="burgerMoto">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ route('about') }}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('services') }}">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('posts.index') }}">View All Posts</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('posts.create') }}">Create</a>
      </li>
    </ul>
  </div>
</nav>

d1/sampleProject/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE-edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@yield('title')</title>
	<!-- font awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

	<link rel="stylesheet" href="{{ asset('/css/app.css') }}">
</head>
<body>
	@include('inc.navbar')

	@yield('content')
	

	<!-- jQuery library -->
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	</script>
</body>
</html>

d1/sampleProject/resources/views/pages/about.blade.php
@extends('layouts.app')

	@section('title')
	About
	@endsection
	
	@section('content')
		<h1> {{ $title }} </h1>

		<p> This is about section </p>
	@endsection

d1/sampleProject/resources/views/pages/index.blade.php
@extends('layouts.app')

	@section('title')
		Index
	@endsection

	@section('content')
	
		<div class="jumbotron">
			<h1>{{ $title }}</h1>
			<p>This website is created using Laravel</p>
		</div>

	@endsection

d1/sampleProject/resources/views/pages/services.blade.php
@extends('layouts.app')

	@section('title')
	Servies
	@endsection
	
	@section('content')
		<h1> {{ $title }} </h1>

		<ul>
			@foreach($services as $service)
				<li>{{$service}}</li>
			@endforeach
		</ul>
	@endsection

d1/sampleProject/resources/views/posts/create.blade.php
@extends('layouts.app')

	@section('title')
		Create Post
	@endsection

	@section('content')
	
		<div class="jumbotron">
			<h1> CREATE KA SIR ??? </h1>
			<div class="container">
				<div class="row">
					<div class="col-md-8 mx-auto col-12">
						@if($errors->any())
							<div class="alert alert-danger">
								<ul>
									@foreach($errors->all() as $error)
										<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
						@endif
						<form method="POST" action="{{ route('posts.store') }}">
							@csrf
							<div class="form-group">
								<label for="title"> Title </label>
								<input type="text" name="title" class="form-control" value="{{ old('title') }}"> 
							</div>
							<div class="form-group">
								<label for="body"> Body </label>
								<textarea name="body" class="form-control" rows="8">{{ old('body') }}</textarea>
							</div>
							<button class="btn btn-outline-dark float-right px-5"> Add Post </button>
						</form>
					</div>
				</div>
			</div>			
		</div>

	@endsection

d1/sampleProject/resources/views/posts/edit.blade.php
@extends('layouts.app')

	@section('title')
		Edit Post
	@endsection

	@section('content')
	
		<div class="jumbotron">
			<h1> EDIT KA SIR ??? </h1>
			<div class="container">
				<div class="row">
					<div class="col-md-8 mx-auto col-12">
						<form method="POST" action="{{ route('posts.update', ['post' => $post->id]) }}">
							@csrf
							@method('PUT')
							<div class="form-group">
								<label for="title"> Title </label>
								<input type="text" name="title" class="form-control" value="{{ $post->title }}"> 
							</div>
							<div class="form-group">
								<label for="body"> Body </label>
								<textarea name="body" class="form-control" rows="8">{{ $post->body }}</textarea>
							</div>
							<button class="btn btn-outline-dark float-right px-5"> Edit Post </button>
						</form>
					</div>
				</div>
			</div>			
		</div>

	@endsection

d1/sampleProject/resources/views/posts/index.blade.php
@extends('layouts.app')

	@section('title')
		Post Index
	@endsection

	@section('content')
	
		<div class="jumbotron">
			<div class="container">
				<div class="row">
					@if(count($posts) > 0)
					@foreach($posts as $post)
						<div class="col-md-6 py-2">
							<div class="card shadow">
								<div class="card-header">
									<a href="{{ route('posts.show', ['post' => $post->id ]) }}"><h1>{{$post->title}}</h1></a>
								</div>
								<div class="card-body">
									<h4>{{$post->body}}</h4>
									<a href="{{ route('posts.edit', ['post' => $post->id]) }}" class="btn btn-info float-right px-5"> Edit </a>
									
									<form action="{{ route('posts.destroy', ['post' => $post->id]) }}" method="POST">
										@csrf
										@method('DELETE')

										<button class="btn btn-danger"> REMOVE </button>
									</form>
								</div>
							</div>
						</div>
					@endforeach
					@else
						<div class="card">
							<div class="card-header">
								<h1>No post</h1>
							</div>
							<div class="card-body">
								<h4>Found</h4>
							</div>
						</div>
					@endif
				</div>
			</div>			
		</div>

	@endsection

d1/sampleProject/resources/views/posts/show.blade.php
@extends('layouts.app')

	@section('title')
		View Post
	@endsection

	@section('content')
	
		<div class="jumbotron">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						@if($post)
							<div class="card">
								<div class="card-header">
									<h1>{{ $post->title }}</h1>
								</div>
								<div class="card-body">
									<h4>{{ $post->body }}</h4>
								</div>
								<div class="card-footer">
									<a class="btn btn-info btn-block" href="{{ route('posts.edit', ['post' => $post->id] ) }}"> Edithh????</a>
								</div>
							</div>
						@else
							<div class="card">
								<div class="card-header">
									<h1>No post</h1>
								</div>
								<div class="card-body">
									<h4>Found</h4>
								</div>
							</div>
						@endif
					</div>
				</div>
			</div>			
		</div>

	@endsection